-- Migration: Add image column and seed 25 exercises (Soft Migration)
ALTER TABLE public.exercise ADD COLUMN image text;

INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Skłony głowy', 'Usiądź prosto, ramiona rozluźnione. Powoli opuść brodę do klatki piersiowej, wytrzymaj 2 sekundy, wróć. Powtórz spokojnie 8-10 razy.', 60, ARRAY['neck'], 'images/neck-nods.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Krążenia ramion', 'Usiądź prosto, ręce luźno wzdłuż ciała. Wykonaj 8 wolnych krążeń ramion do tyłu, potem 8 do przodu. Skup się na pełnym zakresie ruchu.', 45, ARRAY['shoulders'], 'images/shoulder-rolls.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Rozciąganie nadgarstków', 'Wyciągnij prawą rękę przed siebie, dłonią do góry. Drugą ręką delikatnie ściągnij palce w dół, do siebie. Wytrzymaj 20 sekund, zmień rękę.', 60, ARRAY['general'], 'images/wrist-flexor-stretch.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Reguła 20-20-20', 'Oderwij wzrok od ekranu. Spójrz na coś oddalonego o około 6 metrów (okno, ściana w korytarzu) i utrzymaj wzrok przez 20 sekund. Mrugaj normalnie.', 30, ARRAY['eyes'], 'images/20-20-20-eye-rule.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Cofanie brody', 'Usiądź prosto, wzrok przed siebie. Cofnij brodę poziomo do tyłu, jakbyś chciał zrobić sobie podwójny podbródek — głowa nie pochyla się ani w dół ani w górę. Wytrzymaj 5 sekund, rozluźnij. Powtórz 8 razy.', 60, ARRAY['neck', 'general'], 'images/chin-tuck.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Rozciąganie boku szyi', 'Usiądź prosto. Prawą ręką sięgnij górą głowy do lewego ucha i delikatnie pochyl głowę w prawo. Lewa ręka zwisa luźno, ramię w dół. Wytrzymaj 20 sekund, zmień stronę.', 60, ARRAY['neck', 'shoulders'], 'images/upper-trap-stretch.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Rozciąganie szyi w skos', 'Usiądź prosto. Obróć głowę w prawo o około 45 stopni i opuść wzrok w stronę prawej pachy. Lewą ręką delikatnie pociągnij tył głowy w kierunku tej pachy. Wytrzymaj 20 sekund, zmień stronę.', 60, ARRAY['neck', 'shoulders'], 'images/levator-scapulae-stretch.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Wyprost piersiowy w krześle', 'Usiądź na krześle, którego oparcie sięga ci do łopatek. Spleć dłonie za głową, łokcie szeroko. Powoli wygnij górną część pleców do tyłu nad oparciem, patrząc w sufit. Wytrzymaj 5 sekund, wróć. Powtórz 5 razy.', 60, ARRAY['shoulders', 'general'], 'images/thoracic-extension-on-chair.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Łuk i koci grzbiet siedząc', 'Usiądź prosto, dłonie na kolanach. Wdychając, wygnij plecy w łuk — klatka do przodu, broda lekko w górę. Wydychając, zaokrąglij plecy — broda do mostka, łopatki rozejdź na boki. Wykonaj płynnie 8 cykli.', 90, ARRAY['shoulders', 'lower_back', 'general'], 'images/seated-back-arch-and-round.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Skręt kręgosłupa siedząc', 'Usiądź prosto, stopy płasko na podłodze. Prawą rękę połóż na lewym kolanie, lewą za sobą na siedzeniu. Skręć tułów w lewo, prowadząc wzrok za ramieniem. Wytrzymaj 15 sekund, zmień stronę.', 60, ARRAY['shoulders', 'lower_back'], 'images/seated-spinal-twist.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Skłon boczny stojąc', 'Stań prosto, stopy na szerokość bioder. Spleć dłonie i wyciągnij ręce nad głowę. Pochyl tułów w prawo, czując rozciąganie wzdłuż lewego boku. Wytrzymaj 10 sekund, zmień stronę. Powtórz po 2 razy każdą stronę.', 45, ARRAY['shoulders', 'lower_back'], 'images/standing-side-bend.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Mobilizacja nerwu nadgarstka', 'Wyciągnij prawą rękę w bok, dłoń skierowana w górę. Powoli zegnij nadgarstek do tyłu, tak by palce wskazywały w dół, a kciuk w stronę podłogi. Jednocześnie skłoń głowę w lewo. Wytrzymaj 3 sekundy, wróć. Powtórz 8 razy każdą ręką.', 60, ARRAY['general'], 'images/median-nerve-glide.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Gimnastyka ścięgien palców', 'Wyciągnij dłoń z palcami prosto. Następnie zegnij palce w hak (knykcie proste, palce zgięte), potem zaciśnij pełną pięść, otwórz prosto i powtórz. Wykonaj 10 cykli każdą ręką.', 45, ARRAY['general'], 'images/finger-tendon-glide.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Zakrywanie oczu dłońmi', 'Pocieraj dłonie energicznie przez 5 sekund, aż się rozgrzeją. Złóż je w miseczki i przyłóż delikatnie do zamkniętych oczu, nie naciskając gałek. Pozostań w ciemności i cieple przez 30 sekund, oddychając spokojnie.', 45, ARRAY['eyes'], 'images/eye-palming.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Przerzucanie wzroku blisko-daleko', 'Wyciągnij kciuk przed siebie na długość ręki. Skup wzrok na kciuku przez 3 sekundy, potem przerzuć go na coś oddalonego o 5+ metrów (okno, ściana). Trzymaj 3 sekundy. Powtórz 8 razy.', 45, ARRAY['eyes'], 'images/near-far-eye-shifts.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Pozycja czwórki siedząc', 'Usiądź prosto. Połóż prawą kostkę na lewym kolanie tak, by prawe kolano otwierało się na zewnątrz. Pochyl tułów lekko do przodu z prostymi plecami, aż poczujesz rozciąganie w prawym pośladku. Wytrzymaj 30 sekund, zmień stronę.', 90, ARRAY['general'], 'images/seated-figure-4.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Przyciąganie kolan siedząc', 'Usiądź na brzegu krzesła, plecy proste. Złap obiema rękami pod prawym kolanem i przyciągnij je do klatki piersiowej. Wytrzymaj 15 sekund — poczuj rozciąganie w lędźwiach i biodrze. Zmień nogę.', 60, ARRAY['general', 'lower_back'], 'images/seated-knee-hugs.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Krążenia i zginanie stóp', 'Usiądź prosto, unieś prawą stopę nad podłogę. Zegnij i wyprostuj stopę 10 razy (jak naciskanie pedału), potem narysuj 5 kółek w jedną i 5 w drugą stronę. Zmień stopę.', 45, ARRAY['general'], 'images/ankle-pumps-and-circles.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Oddech kwadratowy 4-4-4-4', 'Usiądź prosto, ręce na udach, oczy zamknięte lub spuszczone. Wdech przez nos przez 4 sekundy, zatrzymaj oddech 4 sekundy, wydech ustami 4 sekundy, pauza 4 sekundy. Powtórz 5 razy zachowując równy rytm.', 90, ARRAY['general'], 'images/box-breathing.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Oddech przeponowy', 'Usiądź wygodnie. Połóż jedną rękę na klatce piersiowej, drugą na brzuchu. Wdychaj nosem powoli, kierując powietrze do brzucha — ręka na brzuchu unosi się, ręka na klatce zostaje stabilna. Wydychaj ustami spokojnie. Wykonaj 8 oddechów.', 90, ARRAY['general'], 'images/diaphragmatic-breathing.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Ściąganie łopatek', 'Usiądź lub stań prosto, ramiona luźno. Ściągnij łopatki do siebie i lekko w dół, jakbyś chciał zatrzymać ołówek między nimi. Wytrzymaj 5 sekund, rozluźnij. Powtórz 10 razy. Klatka rozluźniona, szyja nie napina się.', 45, ARRAY['shoulders', 'general'], 'images/shoulder-blade-squeeze.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Anioły przy ścianie', 'Stań plecami do ściany, stopy 15 cm od ściany. Pośladki, plecy i tył głowy dotykają ściany. Wyprostuj ręce na boki, łokcie i grzbiety dłoni przy ścianie. Powoli przesuń ręce w górę nad głowę zachowując kontakt ze ścianą, wróć. Powtórz 8 razy.', 60, ARRAY['shoulders', 'general'], 'images/wall-angels.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Otwarcie klatki w futrynie', 'Stań w drzwiach. Ułóż przedramiona na futrynie po obu stronach, łokcie na wysokości ramion. Wykrocz lekko jedną nogą do przodu, aż poczujesz rozciąganie w klatce piersiowej i przedniej części barków. Wytrzymaj 30 sekund.', 60, ARRAY['shoulders'], 'images/doorway-pec-stretch.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Stretch zginaczy bioder stojąc', 'Stań w niskim wykroku — prawa noga z tyłu, lewa ugięta z przodu. Trzymaj tułów prosto, miednica wsunięta lekko do przodu, pośladek prawy napięty. Poczuj rozciąganie z przodu prawego biodra. Wytrzymaj 30 sekund, zmień nogę.', 90, ARRAY['general'], 'images/standing-hip-flexor-stretch.svg');
INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image) VALUES ('Marsz w miejscu z wspięciami', 'Stań prosto, ręce luźno. Maszeruj w miejscu z wysokim podnoszeniem kolan przez 30 sekund (kolano do wysokości biodra, naprzemiennie). Następnie wykonaj 15 powolnych wspięć na palce. Oddech swobodny.', 60, ARRAY['general'], 'images/march-and-calf-raises.svg');
