-- Migration: Expand exercise catalog and add SVG images
-- Zaktualizować istniejące ćwiczenia nadgarstków z ARRAY['general'] na ARRAY['wrists_hands', 'general']
UPDATE public.exercise SET body_areas = ARRAY['wrists_hands', 'general'] WHERE 'general' = ANY(body_areas) AND (name ILIKE '%dłoń%' OR name ILIKE '%nadgarstk%');

-- Zaktualizować ćwiczenia pośladkowe/biodrowe na ARRAY['glutes_hips', 'lower_back']
UPDATE public.exercise SET body_areas = ARRAY['glutes_hips', 'lower_back'] WHERE 'lower_back' = ANY(body_areas) AND (name ILIKE '%biodr%' OR name ILIKE '%poślad%');

ALTER TABLE public.exercise ADD COLUMN IF NOT EXISTS image text;

INSERT INTO public.exercise (name, description, duration_seconds, body_areas, image)
SELECT * FROM (VALUES
  ('Pozycja gołębia na krześle (Figure-4)', 'Usiądź z prostymi plecami na brzegu krzesła. Połóż prawą kostkę na lewym udzie, tuż nad kolanem. Zrób głęboki wdech i powoli pochyl tułów w przód. Ostrzeżenie: nie garb się i nie naciskaj na kolano.', 60, ARRAY['glutes_hips', 'lower_back']::text[], 'images/seated-figure-4-deep.svg'),
  ('Izometryczne spinanie pośladków', 'Siedząc lub stojąc, zaciśnij mocno mięśnie pośladkowe. Wytrzymaj napięcie przez 5-8 sekund, nie wstrzymując oddechu, po czym powoli rozluźnij. Powtórz 8 razy.', 45, ARRAY['glutes_hips']::text[], 'images/glute-squeezes.svg'),
  ('Wypady przy biurku', 'Stań za biurkiem opierając na nim dłonie. Zrób duży krok w tył jedną nogą i obniż biodra, aż kolano przednie utworzy kąt 90 stopni. Oddychaj miarowo i powróć do pionu.', 60, ARRAY['glutes_hips']::text[], 'images/desk-lunge.svg'),
  ('Siedzący motyl', 'Siedząc głęboko, złącz podeszwy butów (jeśli to możliwe) i pozwól kolanom opaść na boki. Rozciąga to mięśnie przywodziciele i otwiera biodra po długim siedzeniu.', 60, ARRAY['glutes_hips']::text[], 'images/seated-butterfly.svg'),
  ('Przysiad asystowany biurkiem', 'Trzymając się krawędzi biurka, cofnij biodra w tył i powoli zrób głęboki przysiad, utrzymując proste plecy. Wypchnij się w górę z pięt. Poprawia krążenie.', 45, ARRAY['glutes_hips']::text[], 'images/desk-assisted-squat.svg'),
  ('Odwodzenie biodra stojąc', 'Stojąc obok krzesła, unoś prostą nogę w bok na wysokość 30 cm, napinając boczny pośladek. Trzymaj wyprostowany tułów i płynnie wracaj do pozycji wyjściowej.', 60, ARRAY['glutes_hips']::text[], 'images/standing-hip-abduction.svg'),
  ('Rozciąganie pasma biodrowo-piszczelowego', 'Skrzyżuj prawą nogę za lewą. Unieś prawą rękę nad głowę i delikatnie pochyl tułów w lewo. Poczujesz rozciąganie na zewnętrznej stronie prawego uda i biodra.', 45, ARRAY['glutes_hips']::text[], 'images/standing-it-band-stretch.svg'),
  ('Krążenia biodrami na piłce lub krześle', 'Usiądź z szeroko rozstawionymi nogami. Zaczynając od miednicy, powoli zataczaj obszerne koła biodrami, najpierw w jedną, a potem w drugą stronę.', 60, ARRAY['glutes_hips', 'lower_back']::text[], 'images/pelvic-circles.svg'),
  ('Marsz w miejscu z wysokim kolanem', 'Wstań i maszeruj w miejscu, unosząc kolana tak wysoko, aby kąt w biodrze przekroczył 90 stopni. Wzmocnisz w ten sposób zginacze bioder i aktywujesz pośladki.', 60, ARRAY['glutes_hips']::text[], 'images/high-knee-march.svg'),
  ('Stojące kopnięcia w tył', 'Trzymając się biurka, przenoś powoli wyprostowaną nogę w tył, mocno spinając pośladek w końcowej fazie. Nie wyginaj odcinka lędźwiowego. Powtórz dla obu nóg.', 45, ARRAY['glutes_hips']::text[], 'images/standing-kickbacks.svg'),
  ('Siedzące unoszenie kolana', 'Usiądź głęboko na krześle, plecy proste. Unieś złączone zgięte kolana kilka centymetrów nad siedzisko. Wytrzymaj 5 sekund, oddychając przeponą, po czym opuść.', 45, ARRAY['glutes_hips']::text[], 'images/seated-knee-raise.svg'),
  ('Aktywacja mięśnia gruszkowatego', 'Siedząc, załóż prawą nogę na lewą udo. Skręć tułów w prawo, obejmując prawe kolano lewą ręką i przyciągając je do lewego barku. Utrzymaj dla ulgi w rwie kulszowej.', 60, ARRAY['glutes_hips', 'lower_back']::text[], 'images/piriformis-activation.svg'),
  ('Rozciąganie nadgarstków modlitewne (Prayer Stretch)', 'Złącz dłonie przed klatką piersiową, jak do modlitwy. Powoli opuszczaj złączone dłonie w kierunku pępka, utrzymując przedramiona poziomo, aż poczujesz mocne rozciąganie.', 45, ARRAY['wrists_hands']::text[], 'images/prayer-stretch.svg'),
  ('Odwrotne modlitewne rozciąganie', 'Skieruj dłonie grzbietami do siebie przed klatką piersiową i opuść łokcie w dół. To przeciwwaga dla ciągłego pisania na klawiaturze. Wytrzymaj i głęboko oddychaj.', 45, ARRAY['wrists_hands']::text[], 'images/reverse-prayer-stretch.svg'),
  ('Poślizg nerwu łokciowego (Ulnar Glide)', 'Unieś rękę na bok, zagnij łokieć pod kątem 90 stopni. Zrób znak OK palcami, a następnie powoli odginaj nadgarstek w tył, jakbyś trzymał na dłoni małą tacę.', 45, ARRAY['wrists_hands']::text[], 'images/ulnar-nerve-glide.svg'),
  ('Otrzepywanie dłoni z wody', 'Rozluźnij całkowicie nadgarstki i dłonie. Potrząsaj nimi energicznie we wszystkich kierunkach przez 30 sekund, jakbyś chciał strzepnąć z nich kropelki wody po myciu.', 30, ARRAY['wrists_hands']::text[], 'images/hand-wrist-shake.svg'),
  ('Rozkładanie wachlarza palców', 'Zaciśnij mocno dłonie w pięści na 3 sekundy, a następnie błyskawicznie i maksymalnie szeroko rozłóż wszystkie palce, prostując je. Powtórz serię 10 razy.', 45, ARRAY['wrists_hands']::text[], 'images/finger-fan.svg'),
  ('Krążenia w ósemki nadgarstkami', 'Spleć palce dłoni ze sobą. Płynnym ruchem wykonuj złączonymi nadgarstkami znaki nieskończoności (poziome ósemki). Smaruje to stawy po długotrwałym używaniu myszki.', 60, ARRAY['wrists_hands']::text[], 'images/wrist-figure-8.svg'),
  ('Masaż kłębu kciuka (Thenar Massage)', 'Kciukiem lewej ręki głęboko i punktowo masuj mięsistą poduszkę pod prawym kciukiem. To miejsce kumuluje napięcie u osób używających dużo smartfona i myszki.', 60, ARRAY['wrists_hands']::text[], 'images/thenar-massage.svg'),
  ('Biurowe pompki na palcach', 'Oprzyj opuszki palców o krawędź biurka. Powoli przenieś na nie niewielką część ciężaru ciała, prostując palce. Wzmacnia to ścięgna rąk i zapobiega cieśni.', 45, ARRAY['wrists_hands']::text[], 'images/desk-finger-pushups.svg'),
  ('Przeprosty McKenziego na stojąco', 'Wstań, połóż dłonie na odcinku lędźwiowym, nad pośladkami. Powoli i delikatnie wygnij kręgosłup do tyłu, patrząc w sufit. Idealne ćwiczenie kompensacyjne dla siedzenia.', 45, ARRAY['lower_back']::text[], 'images/standing-mckenzie-extension.svg'),
  ('Dekompresja na krześle', 'Opierając dłonie na podłokietnikach lub krawędzi krzesła, wypchnij się w górę tak, by pośladki zawisły nad siedziskiem. Pozwól kręgosłupowi na grawitacyjne rozluźnienie.', 30, ARRAY['lower_back']::text[], 'images/chair-pushup-decompression.svg'),
  ('Zegar miednicy na siedząco', 'Siedząc z prostymi plecami, delikatnie podwijaj kość ogonową pod siebie (zaokrąglając lędźwia), a potem wyginaj lędźwia w łuk (przodopochylenie). Pracuj tylko miednicą.', 60, ARRAY['lower_back']::text[], 'images/pelvic-clock-tilts.svg'),
  ('Podparty opad w przód', 'Oprzyj ręce mocno na biurku. Zrób krok do tyłu i pochyl tułów tak, aby znalazł się równolegle do podłogi, a plecy były proste. Głęboko wydłuż kręgosłup.', 60, ARRAY['lower_back', 'shoulders']::text[], 'images/supported-forward-fold.svg'),
  ('Siedzące sięganie w bok (Lat Reach)', 'Siedząc stabilnie, unieś prawą rękę wysoko w górę i powoli pochyl tułów w lewo, rozciągając cały prawy bok od biodra aż po pachy. Powtórz dla drugiej strony.', 60, ARRAY['lower_back', 'general']::text[], 'images/seated-lat-reach.svg'),
  ('Skręt kręgosłupa z założoną nogą', 'Siedząc, załóż prawą nogę na lewą. Połóż lewą dłoń na prawym kolanie i wykonaj głęboki skręt tułowia w prawo, patrząc za siebie. Oddychaj w brzuch przez 30 sekund na stronę.', 60, ARRAY['lower_back']::text[], 'images/cross-leg-spinal-twist.svg'),
  ('Zwolnienie podpotyliczne', 'Spleć dłonie na karku, pod potylicą. Delikatnie odchyl głowę do tyłu, jednocześnie stawiając umiarkowany opór dłońmi. Odciąża to mięśnie stabilizujące głowę nad ekranem.', 45, ARRAY['neck']::text[], 'images/suboccipital-release.svg'),
  ('Sięganie uchem do barku (Ear-to-Shoulder)', 'Powoli opuść lewe ucho w stronę lewego barku. Prawą rękę wyciągnij w stronę podłogi by pogłębić rozciąganie prawego boku szyi. Utrzymaj po 30 sekund na stronę.', 60, ARRAY['neck']::text[], 'images/ear-shoulder-reach.svg'),
  ('Izometryczna stabilizacja szyi', 'Przyłóż dłoń do czoła. Delikatnie napieraj głową na dłoń i dłonią na głowę, bez żadnego ruchu, przez 5 sekund. Zrób to z każdej z czterech stron głowy.', 60, ARRAY['neck']::text[], 'images/isometric-neck-stabilization.svg'),
  ('Retrakcja szyjna z palcem', 'Połóż palec wskazujący na brodzie. Cofaj głowę poziomo w tył, odsuwając brodę od palca (jak żółw chowający głowę), by utworzyć drugi podbródek. Rozluźnij po 3 sekundach.', 45, ARRAY['neck']::text[], 'images/cervical-retraction.svg'),
  ('Spojrzenie przez ramię', 'Usiądź prosto. Powoli odwracaj głowę w lewo, starając się spojrzeć jak najdalej za swoje lewe ramię, bez rotacji tułowia. Płynnie wróć i powtórz w prawo.', 45, ARRAY['neck']::text[], 'images/over-shoulder-look.svg'),
  ('Rozszerzenie klatki ze splotem', 'Spleć dłonie za plecami i wyprostuj łokcie. Ściągnij łopatki mocno w dół i do siebie, wypychając klatkę piersiową do góry. Przeciwdziała to wdowiemu garbowi.', 60, ARRAY['shoulders', 'general']::text[], 'images/chest-expansion-clasp.svg'),
  ('Z pozycji W do Y', 'Unieś zgięte ręce tak, by przypominały literę W (łopatki ściśnięte). Z wydechem wyprostuj ręce w górę i na boki do litery Y, a z wdechem wróć z mocnym napięciem w dół.', 60, ARRAY['shoulders']::text[], 'images/seated-w-to-y.svg'),
  ('Opadnięcie w dół w biurku (Puppy Sink)', 'Siedząc nieco dalej od biurka, oprzyj złączone dłonie na krawędzi i pozwól klatce piersiowej i głowie opaść swobodnie między ramiona w kierunku podłogi.', 45, ARRAY['shoulders', 'lower_back']::text[], 'images/desk-puppy-sink.svg'),
  ('Rozciąganie naramiennego (Cross-body)', 'Wyprostuj jedną rękę w poprzek klatki piersiowej, tuż pod brodą. Drugą ręką chwyć za łokieć i dociśnij wyprostowane ramię do siebie. Trzymaj bark opuszczony w dół.', 60, ARRAY['shoulders']::text[], 'images/cross-body-deltoid.svg'),
  ('Uścisk brwi i ulga (Brow Pinch)', 'Używając kciuka i palca wskazującego, chwyć i delikatnie uciskaj tkankę brwiową, zaczynając od nasady nosa i posuwając się na zewnątrz. Zdejmuje napięcie z czoła.', 45, ARRAY['eyes', 'neck']::text[], 'images/brow-pinch-release.svg'),
  ('Zegar kształtów oczami', 'Trzymając głowę nieruchomo, wyobraź sobie wielki zegar. Przesuwaj wzrok na godzinę 12, następnie płynnie przez cały cyferblat, skupiając się na płynności śledzenia.', 60, ARRAY['eyes']::text[], 'images/eye-shapes-clock.svg'),
  ('Oddech przywspółczulny (4-7-8)', 'Zrób wdech nosem licząc do 4. Wstrzymaj oddech licząc powoli do 7. Następnie zrób głośny wydech ustami z charakterystycznym świstem, licząc do 8. Zrób 4 pełne cykle.', 90, ARRAY['general']::text[], 'images/parasympathetic-breath-478.svg')
) AS v(name, description, duration_seconds, body_areas, image)
WHERE NOT EXISTS (SELECT 1 FROM public.exercise e WHERE e.name = v.name);
